"use client";

import { useMemo, useState } from "react";

import {
  TutorResponseSchema,
  type Diagnosis,
  type TeachbackEvaluation,
  type TransferEvaluation,
  type TutorResponse,
} from "@/lib/contracts";
import type { Lesson } from "@/lib/lessons";
import { runJavaScript, type RuntimeResult } from "@/lib/runtime";

type Stage =
  | "commit"
  | "hypothesis"
  | "evidence"
  | "repair"
  | "transfer"
  | "complete";

const progress = [
  { id: "commit", label: "Commit" },
  { id: "hypothesis", label: "Hypothesis" },
  { id: "evidence", label: "Evidence" },
  { id: "repair", label: "Repair" },
  { id: "transfer", label: "Transfer" },
] as const;

async function requestTutor(body: unknown): Promise<TutorResponse> {
  const response = await fetch("/api/tutor", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data: unknown = await response.json();

  if (!response.ok) {
    const message =
      typeof data === "object" && data && "error" in data
        ? String(data.error)
        : "The tutor could not complete that step.";
    throw new Error(message);
  }

  const parsed = TutorResponseSchema.safeParse(data);
  if (!parsed.success) {
    throw new Error("The tutor returned an unexpected response.");
  }

  return parsed.data;
}

function orderFromLogs(logs: string[]): string {
  return logs.join("  →  ");
}

function optionMatchesLogs(order: string, logs: string[]): boolean {
  return order.replaceAll(" ", "") === logs.join("→");
}

function CodePanel({ code, label }: { code: string; label: string }) {
  return (
    <section className="code-panel" aria-label={label}>
      <div className="code-panel__bar">
        <span className="window-dots" aria-hidden="true">
          <i />
          <i />
          <i />
        </span>
        <span>{label}</span>
        <span className="language-chip">JS</span>
      </div>
      <pre>
        <code>{code}</code>
      </pre>
    </section>
  );
}

function RuntimeTimeline({ result }: { result: RuntimeResult }) {
  return (
    <div className="runtime" aria-live="polite">
      <div className="runtime__header">
        <span>Recorded runtime</span>
        <span>{result.durationMs} ms</span>
      </div>
      <ol className="runtime__logs">
        {result.logs.map((log, index) => (
          <li key={`${index}-${log}`} style={{ "--delay": `${index * 90}ms` } as React.CSSProperties}>
            <span>{index + 1}</span>
            <code>{log}</code>
          </li>
        ))}
      </ol>
      <div className="runtime__seal">
        <span aria-hidden="true">✓</span>
        Executed in an isolated browser worker — not generated by AI
      </div>
    </div>
  );
}

export function LearningLab({ lesson }: { lesson: Lesson }) {
  const [stage, setStage] = useState<Stage>("commit");
  const [predictionId, setPredictionId] = useState("");
  const [explanation, setExplanation] = useState("");
  const [diagnosis, setDiagnosis] = useState<Diagnosis | null>(null);
  const [runtimeResult, setRuntimeResult] = useState<RuntimeResult | null>(null);
  const [teachback, setTeachback] = useState("");
  const [evaluation, setEvaluation] = useState<TeachbackEvaluation | null>(null);
  const [transferPredictionId, setTransferPredictionId] = useState("");
  const [transferRationale, setTransferRationale] = useState("");
  const [transferResult, setTransferResult] = useState<RuntimeResult | null>(null);
  const [transferEvaluation, setTransferEvaluation] = useState<TransferEvaluation | null>(null);
  const [sessionId] = useState(() => crypto.randomUUID());
  const [mode, setMode] = useState<"demo" | "live" | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const stageIndex = progress.findIndex((item) => item.id === stage);
  const currentStep = stage === "complete" ? progress.length : stageIndex;
  const selectedPrediction = lesson.predictionOptions.find(
    (option) => option.id === predictionId,
  );
  const transferPrediction = lesson.transfer.predictionOptions.find(
    (option) => option.id === transferPredictionId,
  );
  const predictionWasCorrect = useMemo(
    () =>
      Boolean(
        selectedPrediction &&
          runtimeResult &&
          optionMatchesLogs(selectedPrediction.order, runtimeResult.logs),
      ),
    [runtimeResult, selectedPrediction],
  );
  const transferVerified =
    evaluation?.status === "revised" && transferEvaluation?.status === "verified";

  async function diagnose() {
    if (!predictionId || explanation.trim().length < 12) {
      setError("Choose a prediction and explain the rule you used in at least one sentence.");
      return;
    }

    setBusy(true);
    setError("");
    try {
      const response = await requestTutor({
        action: "diagnose",
        sessionId,
        lessonId: lesson.id,
        predictionId,
        explanation,
      });
      if (response.action !== "diagnose") throw new Error("Unexpected tutor step.");
      setDiagnosis(response.result);
      setMode(response.mode);
      setStage("hypothesis");
    } catch (requestError) {
      setError(
        requestError instanceof Error ? requestError.message : "Please try again.",
      );
    } finally {
      setBusy(false);
    }
  }

  async function runCounterexample() {
    setStage("evidence");
    setBusy(true);
    setError("");
    try {
      setRuntimeResult(await runJavaScript(lesson.code));
    } catch (runtimeError) {
      setStage("hypothesis");
      setError(
        runtimeError instanceof Error
          ? runtimeError.message
          : "The experiment could not run.",
      );
    } finally {
      setBusy(false);
    }
  }

  async function evaluateTeachback() {
    if (!diagnosis || !runtimeResult || teachback.trim().length < 12) {
      setError("Explain the corrected rule in at least one sentence.");
      return;
    }

    setBusy(true);
    setError("");
    try {
      const response = await requestTutor({
        action: "evaluate_teachback",
        sessionId,
        lessonId: lesson.id,
        originalExplanation: explanation,
        teachback,
        observation: runtimeResult.logs,
      });
      if (response.action !== "evaluate_teachback") {
        throw new Error("Unexpected tutor step.");
      }
      setEvaluation(response.result);
      setMode(response.mode);
    } catch (requestError) {
      setError(
        requestError instanceof Error ? requestError.message : "Please try again.",
      );
    } finally {
      setBusy(false);
    }
  }

  async function runTransfer() {
    if (!transferPredictionId || transferRationale.trim().length < 12) {
      setError("Commit to a prediction and explain the rule you transferred.");
      return;
    }

    setBusy(true);
    setError("");
    try {
      const runtime = await runJavaScript(lesson.transfer.code);
      setTransferResult(runtime);
      const response = await requestTutor({
        action: "evaluate_transfer",
        sessionId,
        lessonId: lesson.id,
        predictionId: transferPredictionId,
        rationale: transferRationale,
        observation: runtime.logs,
      });
      if (response.action !== "evaluate_transfer") {
        throw new Error("Unexpected tutor step.");
      }
      setTransferEvaluation(response.result);
      setMode(response.mode);
      setStage("complete");
    } catch (runtimeError) {
      setError(
        runtimeError instanceof Error
          ? runtimeError.message
          : "The transfer experiment could not run.",
      );
    } finally {
      setBusy(false);
    }
  }

  function restart() {
    setStage("commit");
    setPredictionId("");
    setExplanation("");
    setDiagnosis(null);
    setRuntimeResult(null);
    setTeachback("");
    setEvaluation(null);
    setTransferPredictionId("");
    setTransferRationale("");
    setTransferResult(null);
    setTransferEvaluation(null);
    setError("");
  }

  return (
    <main className="app-shell">
      <nav className="topbar" aria-label="Primary navigation">
        <a className="brand" href="#top" aria-label="Counterproof home">
          <span className="brand__mark">C<span>P</span></span>
          <span>counterproof</span>
        </a>
        <div className="topbar__right">
          <span className="build-badge"><i /> OpenAI Build Week</span>
          {mode && (
            <span className={`mode-badge mode-badge--${mode}`}>
              {mode === "live" ? "GPT-5.6 live" : "Seeded demo"}
            </span>
          )}
        </div>
      </nav>

      <section className="hero" id="top">
        <div>
          <p className="kicker">Evidence-first learning lab</p>
          <h1>Don’t tell me I’m wrong.<br /><em>Make my model fail.</em></h1>
        </div>
        <p className="hero__copy">
          Counterproof turns a programming belief into a prediction, tests it
          against real execution, and checks whether the corrected idea transfers.
        </p>
      </section>

      <section className="workspace" aria-label="Counterproof learning lab">
        <header className="workspace__header">
          <div>
            <span className="lesson-number">LAB 01</span>
            <div>
              <p>{lesson.eyebrow}</p>
              <h2>{lesson.shortTitle}</h2>
            </div>
          </div>
          <ol className="progress" aria-label="Lesson progress">
            {progress.map((item, index) => (
              <li
                className={index === currentStep ? "is-current" : index < currentStep ? "is-done" : ""}
                key={item.id}
              >
                <span>{index < currentStep ? "✓" : index + 1}</span>
                {item.label}
              </li>
            ))}
          </ol>
        </header>

        <div className="workspace__body">
          <aside className="experiment-column">
            <div className="experiment-column__heading">
              <span>THE EXPERIMENT</span>
              <span className="truth-chip">Execution = evidence</span>
            </div>
            <CodePanel
              code={stage === "transfer" || stage === "complete" ? lesson.transfer.code : lesson.code}
              label={stage === "transfer" || stage === "complete" ? "transfer.js" : "counterexample.js"}
            />
            <div className="guardrail">
              <span aria-hidden="true">⌁</span>
              <div>
                <strong>Two-source design</strong>
                <p>GPT-5.6 reasons about your belief. An isolated, time-limited worker runs an audited code fixture.</p>
              </div>
            </div>
          </aside>

          <section className="lesson-card">
            {stage === "commit" && (
              <div className="stage stage--commit">
                <p className="stage-label">01 · COMMIT YOUR MODEL</p>
                <h3>{lesson.title}</h3>
                <p className="stage-intro">{lesson.setup}</p>

                <fieldset className="prediction-grid">
                  <legend>{lesson.question}</legend>
                  {lesson.predictionOptions.map((option, index) => (
                    <label key={option.id} className={predictionId === option.id ? "is-selected" : ""}>
                      <input
                        type="radio"
                        name="prediction"
                        value={option.id}
                        checked={predictionId === option.id}
                        onChange={() => setPredictionId(option.id)}
                      />
                      <span className="option-letter">{String.fromCharCode(65 + index)}</span>
                      <code>{option.order}</code>
                      <span className="radio-dot" />
                    </label>
                  ))}
                </fieldset>

                <div className="text-field">
                  <div className="text-field__header">
                    <label htmlFor="belief-explanation">What rule did you use?</label>
                    <button type="button" onClick={() => setExplanation(lesson.suggestedExplanation)}>
                      Use a sample belief
                    </button>
                  </div>
                  <textarea
                    id="belief-explanation"
                    value={explanation}
                    onChange={(event) => setExplanation(event.target.value)}
                    placeholder="I think the order is ... because await ..."
                    maxLength={1200}
                    rows={5}
                  />
                  <small>{explanation.length} / 1200</small>
                </div>

                <button className="primary-button" type="button" onClick={diagnose} disabled={busy}>
                  {busy ? "Forming a hypothesis…" : "Lock prediction"}
                  <span aria-hidden="true">→</span>
                </button>
              </div>
            )}

            {stage === "hypothesis" && diagnosis && (
              <div className="stage stage--hypothesis">
                <p className="stage-label">02 · FALSIFIABLE HYPOTHESIS</p>
                <div className="confidence-row">
                  <span>MODEL CONFIDENCE</span>
                  <strong>{Math.round(diagnosis.confidence * 100)}%</strong>
                </div>
                <div className="belief-card">
                  <span className="belief-card__pin">YOUR BELIEF</span>
                  <blockquote>{diagnosis.hypothesis}</blockquote>
                </div>
                <div className="diagnosis-copy">
                  <h3>{diagnosis.misconception}</h3>
                  <p>{diagnosis.whyItFeelsRight}</p>
                </div>
                <div className="question-callout">
                  <span>?</span>
                  <p>{diagnosis.discriminatingQuestion}</p>
                </div>
                <button className="primary-button" type="button" onClick={runCounterexample} disabled={busy}>
                  Run the counterexample
                  <span aria-hidden="true">▶</span>
                </button>
                <p className="button-note">The output is captured locally, not predicted by GPT-5.6.</p>
              </div>
            )}

            {stage === "evidence" && (
              <div className="stage stage--evidence">
                <p className="stage-label">03 · OBSERVE THE EVIDENCE</p>
                {busy && !runtimeResult ? (
                  <div className="running-state">
                    <span className="running-orbit" />
                    <h3>Running the smallest useful test…</h3>
                    <p>Audited fixture · output capped · hard timeout enabled</p>
                  </div>
                ) : runtimeResult ? (
                  <>
                    <div className="comparison">
                      <div>
                        <span>Your prediction</span>
                        <strong>{selectedPrediction?.order}</strong>
                      </div>
                      <div className={predictionWasCorrect ? "is-match" : "is-conflict"}>
                        <span>Observed</span>
                        <strong>{orderFromLogs(runtimeResult.logs)}</strong>
                      </div>
                    </div>
                    <RuntimeTimeline result={runtimeResult} />
                    <div className={`verdict ${predictionWasCorrect ? "verdict--match" : "verdict--conflict"}`}>
                      <span>{predictionWasCorrect ? "✓" : "↯"}</span>
                      <div>
                        <strong>{predictionWasCorrect ? "Prediction matched" : "Counterexample found"}</strong>
                        <p>
                          {predictionWasCorrect
                            ? "Now explain the mechanism, not just the correct order."
                            : `The runtime printed ${orderFromLogs(runtimeResult.logs)}. Your rule needs one precise repair.`}
                        </p>
                      </div>
                    </div>
                    <button className="primary-button" type="button" onClick={() => setStage("repair")}>
                      Repair my model <span aria-hidden="true">→</span>
                    </button>
                  </>
                ) : null}
              </div>
            )}

            {stage === "repair" && diagnosis && runtimeResult && (
              <div className="stage stage--repair">
                <p className="stage-label">04 · TEACH IT BACK</p>
                <h3>Rewrite the rule using the evidence.</h3>
                <p className="stage-intro">
                  Why did <code>C</code> appear before <code>D</code>? Explain it to a learner who held your original belief.
                </p>
                <div className="evidence-ribbon">
                  <span>RECORDED</span>
                  <code>{orderFromLogs(runtimeResult.logs)}</code>
                </div>
                <div className="text-field">
                  <div className="text-field__header">
                    <label htmlFor="teachback">Your corrected mental model</label>
                  </div>
                  <textarea
                    id="teachback"
                    value={teachback}
                    onChange={(event) => setTeachback(event.target.value)}
                    placeholder="await pauses ... while ..."
                    maxLength={1200}
                    rows={6}
                  />
                  <small>{teachback.length} / 1200</small>
                </div>
                {!evaluation ? (
                  <button className="primary-button" type="button" onClick={evaluateTeachback} disabled={busy}>
                    {busy ? "Checking the causal rule…" : "Check my teach-back"}
                    <span aria-hidden="true">→</span>
                  </button>
                ) : (
                  <div className={`evaluation evaluation--${evaluation.status}`}>
                    <div className="evaluation__status">
                      <span>{evaluation.status === "revised" ? "✓" : "~"}</span>
                      <div>
                        <small>MENTAL MODEL</small>
                        <strong>{evaluation.status}</strong>
                      </div>
                    </div>
                    <p>{evaluation.feedback}</p>
                    <div className="corrected-rule">
                      <span>Portable rule</span>
                      <p>{evaluation.correctedRule}</p>
                    </div>
                    <button
                      className="primary-button"
                      type="button"
                      onClick={() => {
                        if (evaluation.status === "revised") setStage("transfer");
                        else setEvaluation(null);
                      }}
                    >
                      {evaluation.status === "revised" ? "Try a fresh case" : "Revise my explanation"}
                      <span aria-hidden="true">→</span>
                    </button>
                  </div>
                )}
              </div>
            )}

            {stage === "transfer" && (
              <div className="stage stage--transfer">
                <p className="stage-label">05 · TRANSFER CHECK</p>
                <h3>{lesson.transfer.title}</h3>
                <p className="stage-intro">{lesson.transfer.setup}</p>
                <fieldset className="prediction-grid prediction-grid--compact">
                  <legend>What prints now?</legend>
                  {lesson.transfer.predictionOptions.map((option, index) => (
                    <label key={option.id} className={transferPredictionId === option.id ? "is-selected" : ""}>
                      <input
                        type="radio"
                        name="transfer-prediction"
                        checked={transferPredictionId === option.id}
                        onChange={() => setTransferPredictionId(option.id)}
                      />
                      <span className="option-letter">{String.fromCharCode(65 + index)}</span>
                      <code>{option.order}</code>
                      <span className="radio-dot" />
                    </label>
                  ))}
                </fieldset>
                <div className="text-field">
                  <div className="text-field__header">
                    <label htmlFor="transfer-rationale">Why will that order happen?</label>
                  </div>
                  <textarea
                    id="transfer-rationale"
                    value={transferRationale}
                    onChange={(event) => setTransferRationale(event.target.value)}
                    placeholder="The surrounding code continues because ..."
                    maxLength={1200}
                    rows={4}
                  />
                  <small>{transferRationale.length} / 1200</small>
                </div>
                <button className="primary-button" type="button" onClick={runTransfer} disabled={busy}>
                  {busy ? "Testing prediction and reason…" : "Commit reason & run"}
                  <span aria-hidden="true">▶</span>
                </button>
              </div>
            )}

            {stage === "complete" && transferResult && transferEvaluation && evaluation && diagnosis && (
              <div className="stage stage--complete">
                <div className={`mastery-mark ${transferVerified ? "is-mastered" : "needs-review"}`}>
                  <span>{transferVerified ? "✓" : "↺"}</span>
                </div>
                <p className="stage-label">SESSION EVIDENCE</p>
                <h3>{transferVerified ? "Your model transferred." : "One more counterexample will help."}</h3>
                <p className="stage-intro">
                  {transferVerified
                    ? "Your prediction matched unfamiliar code and your explanation preserved the causal mechanism."
                    : transferEvaluation.feedback}
                </p>
                <div className="evidence-chain">
                  <div><span>01</span><p><small>Original belief</small>{diagnosis.hypothesis}</p></div>
                  <div><span>02</span><p><small>Prediction ↯ observation</small>{selectedPrediction?.order} · observed {orderFromLogs(runtimeResult?.logs ?? [])}</p></div>
                  <div><span>03</span><p><small>Your repaired explanation</small>{teachback}</p></div>
                  <div><span>04</span><p><small>Transfer prediction ↔ observation</small>{transferPrediction?.order} · observed {orderFromLogs(transferResult.logs)} · {transferEvaluation.status}</p></div>
                </div>
                <div className="final-verdict">
                  <span>{transferVerified ? "TRANSFER VERIFIED" : "REVIEW RECOMMENDED"}</span>
                  <strong>{transferVerified ? "Evidence beats fluency." : "A miss is useful evidence."}</strong>
                </div>
                <button className="secondary-button" type="button" onClick={restart}>
                  Run the lesson again
                </button>
              </div>
            )}

            {error && <p className="error-message" role="alert">{error}</p>}
          </section>
        </div>
      </section>

      <footer>
        <p>Built with Codex + GPT-5.6</p>
        <p>Execution is evidence. Explanations are hypotheses.</p>
      </footer>
    </main>
  );
}
